name: Container

on:
  - pull_request
  - push

permissions:
  contents: read

jobs:
  container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build container
        uses: docker/build-push-action@v5
        with:
          file: Containerfile
          tags: postgresql-evr:latest
